"""Traduções editoriais revisadas para os patches B134 e B135."""

from __future__ import annotations

import re
from typing import Any


TRADUCOES: dict[str, tuple[str, str]] = {
    # Navegação e termos editoriais
    "Highlights": ("Destaques", "Destacados"),
    "Schedule": ("Período", "Periodo"),
    "Season Rewards": ("Recompensas da Temporada", "Recompensas de la Temporada"),
    "Dungeons & Content": ("Dungeons e Conteúdo", "Dungeons y Contenido"),
    "Dungeons": ("Dungeons", "Dungeons"),
    "Dungeons & difficulty tiers": ("Dungeons e níveis de dificuldade", "Dungeons y niveles de dificultad"),
    "Dungeons and difficulty tiers": ("Dungeons e níveis de dificuldade", "Dungeons y niveles de dificultad"),
    "Accessory Runes": ("Runas de Acessório", "Runas de Accesorio"),
    "Classes": ("Classes", "Clases"),
    "Class Balance": ("Balanceamento de Classes", "Balance de Clases"),
    "Rewards": ("Recompensas", "Recompensas"),
    "Stat Scaling": ("Escalonamento de Atributos", "Escalado de Atributos"),
    "Items": ("Itens", "Ítems"),
    "System & Fixes": ("Sistema e Correções", "Sistema y Correcciones"),
    "Item": ("Item", "Ítem"),
    "Qty": ("Qtd.", "Cant."),
    "Level": ("Nível", "Nivel"),
    "Free Rewards": ("Recompensas Gratuitas", "Recompensas Gratuitas"),
    "Premium Rewards": ("Recompensas Premium", "Recompensas Premium"),
    "Enhance": ("Aprimoramento", "Mejora"),
    "Weapon": ("Arma", "Arma"),
    "Armor": ("Armadura", "Armadura"),
    "Shoes/Gloves": ("Botas/Luvas", "Botas/Guantes"),
    "Currency": ("Moeda", "Moneda"),
    "Reset": ("Reinício", "Reinicio"),
    "Gear": ("Equipamentos", "Equipamiento"),
    "Price": ("Preço", "Precio"),
    "Purchase Limit": ("Limite de compra", "Límite de compra"),
    "Enhancement Materials": ("Materiais de Aprimoramento", "Materiales de Mejora"),
    "Other": ("Outros", "Otros"),
    "Quest": ("Missão", "Misión"),
    "Dungeon": ("Dungeon", "Dungeon"),
    "Item Level": ("Nível de item", "Nivel de ítem"),
    "Recommended Players": ("Grupo recomendado", "Grupo recomendado"),
    "Description": ("Descrição", "Descripción"),
    "Type": ("Tipo", "Tipo"),
    "Level 1~5 Effect": ("Efeito dos níveis 1~5", "Efecto de los niveles 1~5"),
    "Applicable Class": ("Classe aplicável", "Clase aplicable"),
    "All": ("Todos", "Todos"),
    "All Classes": ("Todas as classes", "Todas las clases"),
    "Skill": ("Skill", "Skill"),
    "Value": ("Valor", "Valor"),
    "Effect": ("Efeito", "Efecto"),
    "Damage Increase": ("Aumento de dano", "Aumento de daño"),
    "Duration Increase": ("Aumento de duração", "Aumento de duración"),
    "Cast Time Reduction": ("Redução do tempo de conjuração", "Reducción del tiempo de lanzamiento"),
    "Healing Increase": ("Aumento de cura", "Aumento de curación"),
    "Bug fixes": ("Correções de bugs", "Correcciones de bugs"),
    "Not specified": ("Não informado", "No especificado"),
    "Imagem com recompensas": ("Imagem das recompensas", "Imagen de las recompensas"),
    "Imagem dos equipamentos de demonstração": ("Imagem dos equipamentos fornecidos", "Imagen del equipamiento proporcionado"),
    "Imagem dos stigmas de demonstrados": ("Imagem dos Stigmas fornecidos", "Imagen de los Stigmas proporcionados"),
    "Imagem das 5 cartas": ("Imagem das cinco Cartas", "Imagen de las cinco Cartas"),
    "Imagem das novas Runas de acessórios": ("Imagem das novas Runas de Acessório", "Imagen de las nuevas Runas de Accesorio"),
    "Imagem com exemplo de refinamento das Runas de Acessórios": ("Exemplo de evolução das Runas de Acessório", "Ejemplo de evolución de las Runas de Accesorio"),
    "Imagem exemplificando as opções das Runas de Acessórios": ("Exemplo das opções das Runas de Acessório", "Ejemplo de las opciones de las Runas de Accesorio"),
    "Imagem com demonstrando a explosão": ("Demonstração da explosão de Runemarks", "Demostración de la explosión de Runemarks"),
    "Imagem com a skill Godsfall sendo exibida": ("Demonstração da skill Godsfall", "Demostración de la skill Godsfall"),
    "Imagem com a skill Shining Crescent sendo exibida": ("Demonstração da skill Shining Crescent", "Demostración de la skill Shining Crescent"),
    "Imagem exibindo os status": ("Exibição dos atributos", "Visualización de los atributos"),

    # B134 - visão geral e Battle Pass
    "B134 at a glance": ("B134 em resumo", "Resumen de B134"),
    "What changes your progression": ("O que muda na sua progressão", "Qué cambia en tu progresión"),
    "Battle Pass Season 22 begins with 50 reward levels.": ("A Temporada 22 do Battle Pass começa com 50 níveis de recompensas.", "La Temporada 22 del Battle Pass comienza con 50 niveles de recompensas."),
    "Season 2 equipment can be dismantled for Forgotten Steel Fragments.": ("Equipamentos da Temporada 2 podem ser desmontados em Forgotten Steel Fragments.", "El equipamiento de la Temporada 2 se puede desmantelar para obtener Forgotten Steel Fragments."),
    "Dungeon rotations and matchmaking-only rewards have been reorganized.": ("As rotações de Dungeons e as recompensas exclusivas do matchmaking foram reorganizadas.", "Se reorganizaron las rotaciones de Dungeons y las recompensas exclusivas del matchmaking."),
    "What changes your build": ("O que muda na sua build", "Qué cambia en tu build"),
    "Accessory Runes add base stats and class-specific skill effects.": ("As Runas de Acessório adicionam atributos básicos e efeitos de skills específicos de cada classe.", "Las Runas de Accesorio añaden atributos básicos y efectos de skills específicos de cada clase."),
    "Heroic Oath and Kaia's Fury enhancement become easier.": ("O aprimoramento de Heroic Oath e Kaia's Fury ficou mais acessível.", "La mejora de Heroic Oath y Kaia's Fury ahora es más accesible."),
    "Valkyrie receives a major Godsfall and Ragnarok rework.": ("A Valkyrie recebeu uma reformulação importante em Godsfall e Ragnarok.", "La Valkyrie recibió una importante renovación de Godsfall y Ragnarok."),
    "The HARD difficulty system announced for B134 was postponed to the next update.": ("O sistema de dificuldade HARD anunciado para o B134 foi adiado para o próximo update.", "El sistema de dificultad HARD anunciado para B134 se aplazó hasta el próximo update."),
    "Battle Pass Season 22": ("Battle Pass - Temporada 22", "Battle Pass - Temporada 22"),
    "Sale period": ("Período de venda", "Periodo de venta"),
    "After Aug. 27, 2026 maintenance through Jan. 3, 2027": ("Após a manutenção de 27 de agosto de 2026 até 3 de janeiro de 2027", "Desde la finalización del mantenimiento del 27 de agosto de 2026 hasta el 3 de enero de 2027"),
    "Active period": ("Período ativo", "Periodo activo"),
    "After Aug. 27, 2026 maintenance until before Jan. 7, 2027 maintenance": ("Após a manutenção de 27 de agosto de 2026 até antes da manutenção de 7 de janeiro de 2027", "Desde la finalización del mantenimiento del 27 de agosto de 2026 hasta antes del mantenimiento del 7 de enero de 2027"),
    "Battle Pass PLUS Premium contents": ("Conteúdo do Battle Pass PLUS Premium", "Contenido del Battle Pass PLUS Premium"),
    "These bonus rewards are granted when the item is used.": ("Estas recompensas adicionais são concedidas ao usar o item.", "Estas recompensas adicionales se reciben al usar el ítem."),
    "Season 22 level rewards": ("Recompensas por nível da Temporada 22", "Recompensas por nivel de la Temporada 22"),
    "Known bug: additional item claims are temporarily disabled after level 50. Accumulated rewards will be granted together in the next build update.": ("Bug conhecido: o resgate de itens adicionais ficará temporariamente desativado após o nível 50. As recompensas acumuladas serão entregues de uma só vez no próximo update.", "Bug conocido: el reclamo de ítems adicionales quedará desactivado temporalmente después del nivel 50. Las recompensas acumuladas se entregarán juntas en el próximo update."),

    # B134 - temporada e loja
    "Season 2 equipment conversion": ("Conversão dos equipamentos da Temporada 2", "Conversión del equipamiento de la Temporada 2"),
    "What happens to Season 2 equipment": ("O que acontece com os equipamentos da Temporada 2", "Qué ocurre con el equipamiento de la Temporada 2"),
    "[Season 2] Equipment can now be dismantled.": ("Os equipamentos da Temporada 2 agora podem ser desmontados.", "El equipamiento de la Temporada 2 ahora se puede desmantelar."),
    "Enhancement will no longer be possible.": ("Não será mais possível aprimorá-los.", "Ya no será posible mejorarlos."),
    "All main options will be removed.": ("Todos os atributos principais serão removidos.", "Se eliminarán todos los atributos principales."),
    "Forgotten Steel Fragments by enhancement level": ("Forgotten Steel Fragments por nível de aprimoramento", "Forgotten Steel Fragments por nivel de mejora"),
    "Visit Laura (Elin) in Highwatch to exchange your season rewards.": ("Visite Laura (Elin), em Highwatch, para trocar suas recompensas da temporada.", "Visita a Laura (Elin) en Highwatch para canjear tus recompensas de temporada."),
    "Laura (Elin), the Season Reward exchange NPC in Highwatch.": ("Laura (Elin), NPC de troca das recompensas da temporada em Highwatch.", "Laura (Elin), NPC de canje de recompensas de temporada en Highwatch."),
    "Season Reward Shop": ("Loja de Recompensas da Temporada", "Tienda de Recompensas de Temporada"),
    "Purchase counts will be reset": ("Os limites de compra serão reiniciados", "Los límites de compra se reiniciarán"),

    # B134 - conteúdo e dungeons
    "Content and dungeon rotation": ("Conteúdo e rotação de Dungeons", "Contenido y rotación de Dungeons"),
    "The Guardian Training V (Instance Matching) quest will temporarily be completed immediately upon speaking.": ("A missão Guardian Training V (Instance Matching) será concluída temporariamente assim que você conversar com o NPC.", "La misión Guardian Training V (Instance Matching) se completará temporalmente al hablar con el NPC."),
    "Dungeons going offline": ("Dungeons removidas da rotação", "Dungeons retiradas de la rotación"),
    "Difficulty will be reset. Reset Scroll shop entries change to the normal rotation; matchmaking-only dungeons are excluded.": ("A dificuldade será reiniciada. A loja de Reset Scroll passará a oferecer as Dungeons da rotação normal; as exclusivas de matchmaking não estão incluídas.", "La dificultad se reiniciará. La tienda de Reset Scroll pasará a ofrecer las Dungeons de la rotación normal; no se incluyen las exclusivas de matchmaking."),
    "Normal dungeon rotation": ("Rotação normal de Dungeons", "Rotación normal de Dungeons"),
    "Entry is available via normal matchmaking, party recruiting, or Dimensional Gems. Achievements change from Forgotten to Active.": ("A entrada está disponível por matchmaking normal, recrutamento de grupo ou Dimensional Gems. As conquistas passam de Esquecidas para Ativas.", "Se puede entrar mediante matchmaking normal, reclutamiento de grupo o Dimensional Gems. Los logros pasan de Olvidados a Activos."),
    "Matchmaking-only rotation": ("Rotação exclusiva de matchmaking", "Rotación exclusiva de matchmaking"),
    "Available from the 'Matchmaking-Only Dungeons' tab in the matchmaking UI.": ("Disponível na aba 'Dungeons Exclusivas de Matchmaking' da interface.", "Disponible en la pestaña 'Dungeons Exclusivas de Matchmaking' de la interfaz."),
    "A shared 2-entry limit applies. Healers and Tanks receive a +100% bonus entry multiplier.": ("Há um limite compartilhado de 2 entradas. Healers e Tanks recebem um bônus de +100% na quantidade de entradas.", "Se aplica un límite compartido de 2 entradas. Healers y Tanks reciben un bono de +100% en la cantidad de entradas."),
    "Entry via Dimensional Gems is not allowed. Item level 450+ and character level 65+ required.": ("Não é possível entrar com Dimensional Gems. Requer nível de item 450+ e personagem no nível 65+.", "No se permite entrar con Dimensional Gems. Requiere nivel de ítem 450+ y personaje de nivel 65+."),
    "The actual dungeon difficulty is equivalent to level 850.": ("A dificuldade real das Dungeons equivale ao nível 850.", "La dificultad real de las Dungeons equivale al nivel 850."),
    "Official overview of matchmaking-only dungeon rewards.": ("Visão oficial das recompensas das Dungeons exclusivas de matchmaking.", "Resumen oficial de las recompensas de las Dungeons exclusivas de matchmaking."),
    "Provided equipment": ("Equipamentos fornecidos", "Equipamiento proporcionado"),
    "Standardized equipment and Stigmas are provided in auto matchmaking dungeons.": ("Equipamentos e Stigmas padronizados são fornecidos nas Dungeons de matchmaking automático.", "Se proporciona equipamiento y Stigmas estandarizados en las Dungeons de matchmaking automático."),
    "Equipment provided in auto matchmaking dungeons.": ("Equipamentos fornecidos nas Dungeons de matchmaking automático.", "Equipamiento proporcionado en las Dungeons de matchmaking automático."),
    "Stigmas provided in auto matchmaking dungeons.": ("Stigmas fornecidos nas Dungeons de matchmaking automático.", "Stigmas proporcionados en las Dungeons de matchmaking automático."),
    "Matchmaking-only rewards": ("Recompensas exclusivas de matchmaking", "Recompensas exclusivas de matchmaking"),
    "Final boss drops": ("Drops do chefe final", "Drops del jefe final"),
    "The HARD difficulty system planned for B134 was postponed to the next update due to system reorganization.": ("O sistema de dificuldade HARD planejado para o B134 foi adiado para o próximo update devido à reorganização do sistema.", "El sistema de dificultad HARD previsto para B134 se aplazó al próximo update debido a la reorganización del sistema."),
    "Achievements and cards": ("Conquistas e Cartas", "Logros y Cartas"),
    "The achievement season will change, and the target score per tier will increase by the total score of unlocked achievements.": ("A temporada de conquistas mudará, e a pontuação exigida em cada categoria aumentará conforme o total das conquistas liberadas.", "La temporada de logros cambiará y la puntuación requerida por categoría aumentará según el total de logros desbloqueados."),
    "Inappropriate items will be removed from some achievements.": ("Itens inadequados serão removidos de algumas conquistas.", "Se eliminarán ítems inadecuados de algunos logros."),
    "Titles previously displayed in black in the achievement title selection UI will be changed to white.": ("Os títulos exibidos em preto na seleção de títulos de conquistas passarão a ser exibidos em branco.", "Los títulos mostrados en negro en la selección de títulos de logros pasarán a mostrarse en blanco."),
    "The legendary set collection 'Blessing of Shakan' will be subdivided into 5 stages of 5 levels each, with effects distributed every 5 levels.": ("A coleção de conjunto lendária 'Blessing of Shakan' será dividida em 5 etapas de 5 níveis, com efeitos distribuídos a cada 5 níveis.", "La colección de conjunto legendaria 'Blessing of Shakan' se dividirá en 5 etapas de 5 niveles, con efectos cada 5 niveles."),
    "The five stages of the Blessing of Shakan legendary card collection.": ("As cinco etapas da coleção de Cartas lendárias Blessing of Shakan.", "Las cinco etapas de la colección de Cartas legendarias Blessing of Shakan."),
    "Battleground and gear": ("Battleground e equipamentos", "Battleground y equipamiento"),
    "The Beach Water Balloon battleground will be turned OFF.": ("O Battleground Beach Water Balloon será desativado.", "El Battleground Beach Water Balloon será desactivado."),
    "All etchings obtained from the Beach Water Balloon event battleground will be deleted.": ("Todos os Etchings obtidos no evento Beach Water Balloon serão removidos.", "Se eliminarán todos los Etchings obtenidos en el evento Beach Water Balloon."),
    "The base enhancement rate for some equipment will increase and costs will slightly decrease.": ("A chance base de aprimoramento de alguns equipamentos aumentará, e os custos serão levemente reduzidos.", "La probabilidad base de mejora de algunos equipos aumentará y los costes se reducirán ligeramente."),
    "Heroic Oath equipment": ("Equipamentos Heroic Oath", "Equipamiento Heroic Oath"),
    "Kaia's Fury equipment": ("Equipamentos Kaia's Fury", "Equipamiento Kaia's Fury"),

    # B134 - Runas
    "Accessory Runes are a new progression layer: stronger evolutions of accessory crystals that combine base stats with class skill effects.": ("As Runas de Acessório são uma nova camada de progressão: evoluções mais fortes dos cristais de acessórios, combinando atributos básicos com efeitos de skills da classe.", "Las Runas de Accesorio son una nueva capa de progresión: evoluciones más potentes de los cristales de accesorios que combinan atributos básicos con efectos de skills de clase."),
    "Rune behavior and new items": ("Funcionamento das Runas e novos itens", "Funcionamiento de las Runas y nuevos ítems"),
    "After locking a Rune effect and changing it, the locked state will no longer be released and will remain locked.": ("Ao bloquear um efeito de Runa e alterar as opções, o efeito continuará bloqueado.", "Al bloquear un efecto de Runa y cambiar las opciones, el efecto permanecerá bloqueado."),
    "New item Accessory Rune will be added.": ("O novo item Runa de Acessório será adicionado.", "Se añadirá el nuevo ítem Runa de Accesorio."),
    "New Accessory Runes.": ("Novas Runas de Acessório.", "Nuevas Runas de Accesorio."),
    "Increases STR by 4.": ("Aumenta a Força em 4.", "Aumenta la Fuerza en 4."),
    "Increases Toughness and Crit Resistance by 8.": ("Aumenta a Resistência e a Resistência Crítica em 8.", "Aumenta la Resistencia y la Resistencia Crítica en 8."),
    "Increases Crit Factor by 8.": ("Aumenta o Fator Crítico em 8.", "Aumenta el Factor Crítico en 8."),
    "Increases Attack Speed by 1.2%.": ("Aumenta a Velocidade de Ataque em 1,2%.", "Aumenta la Velocidad de Ataque en un 1,2 %."),
    "Increases HP Recovery and Shield effectiveness by 3%.": ("Aumenta a Recuperação de HP e a eficácia de Escudos em 3%.", "Aumenta la Recuperación de HP y la eficacia de los Escudos en un 3 %."),
    "Increases Toughness by 4 and Aggro by an additional 11%.": ("Aumenta a Resistência em 4 e o Aggro em mais 11%.", "Aumenta la Resistencia en 4 y el Aggro en un 11 % adicional."),
    "Crafting and growth": ("Crafting e evolução", "Crafting y evolución"),
    "Combining an accessory artifact using a Succession Runestone grants a succession effect.": ("Combinar um artefato de acessório usando uma Succession Runestone concede um efeito de sucessão.", "Combinar un artefacto de accesorio con una Succession Runestone otorga un efecto de sucesión."),
    "Combining an accessory artifact using a Runestone grants a random Accessory Rune.": ("Combinar um artefato de acessório usando uma Runestone concede uma Runa de Acessório aleatória.", "Combinar un artefacto de accesorio con una Runestone otorga una Runa de Accesorio aleatoria."),
    "The following artifacts grant a random Rune even when using a Succession Runestone.": ("Os artefatos abaixo concedem uma Runa aleatória mesmo ao usar uma Succession Runestone.", "Los siguientes artefactos otorgan una Runa aleatoria incluso al usar una Succession Runestone."),
    "Rune growth follows the same crafting recipe, but additionally requires the new item 'Ancient Freshness Rune Energy'.": ("A evolução da Runa usa a mesma receita de crafting, mas também exige o novo item 'Ancient Freshness Rune Energy'.", "La evolución de la Runa usa la misma receta de crafting, pero también requiere el nuevo ítem 'Ancient Freshness Rune Energy'."),
    "Example of Accessory Rune crafting and growth.": ("Exemplo de crafting e evolução das Runas de Acessório.", "Ejemplo de crafting y evolución de Runas de Accesorio."),
    "How additional options work": ("Como funcionam as opções adicionais", "Cómo funcionan las opciones adicionales"),
    "Examples of Accessory Rune options.": ("Exemplos de opções das Runas de Acessório.", "Ejemplos de opciones de Runas de Accesorio."),
    "In addition to base stat effects, you can randomly obtain skill effects suited to your class.": ("Além dos atributos básicos, você pode obter aleatoriamente efeitos de skills adequados à sua classe.", "Además de los atributos básicos, puedes obtener aleatoriamente efectos de skills apropiados para tu clase."),
    "At maximum growth, a Rune grants 3 additional effects.": ("No nível máximo de evolução, uma Runa concede 3 efeitos adicionais.", "En el nivel máximo de evolución, una Runa otorga 3 efectos adicionales."),
    "Class-specific Rune options": ("Opções de Runa específicas por classe", "Opciones de Runa específicas por clase"),
    "STR +2 / 4 / 6 / 8 / 10": ("Força +2 / 4 / 6 / 8 / 10", "Fuerza +2 / 4 / 6 / 8 / 10"),
    "Crit Factor +4 / 8 / 12 / 16 / 20": ("Fator Crítico +4 / 8 / 12 / 16 / 20", "Factor Crítico +4 / 8 / 12 / 16 / 20"),
    "Damage Amplification +0.5 / 1 / 1.5 / 2 / 2.5%": ("Amplificação de Dano +0,5 / 1 / 1,5 / 2 / 2,5%", "Amplificación de Daño +0,5 / 1 / 1,5 / 2 / 2,5 %"),
    "Toughness +4 / 8 / 12 / 16 / 20": ("Resistência +4 / 8 / 12 / 16 / 20", "Resistencia +4 / 8 / 12 / 16 / 20"),
    "Crit Resistance +4 / 8 / 12 / 16 / 20": ("Resistência Crítica +4 / 8 / 12 / 16 / 20", "Resistencia Crítica +4 / 8 / 12 / 16 / 20"),
    "Combat Move Speed +2 / 4 / 6 / 8 / 10": ("Velocidade de Movimento em Combate +2 / 4 / 6 / 8 / 10", "Velocidad de Movimiento en Combate +2 / 4 / 6 / 8 / 10"),
    "Damage on Block reduced by 200 / 400 / 600 / 800 / 1000": ("Dano ao Bloquear reduzido em 200 / 400 / 600 / 800 / 1.000", "Daño al Bloquear reducido en 200 / 400 / 600 / 800 / 1000"),

    # B134 - classes e sistema
    "Latency and class changes": ("Latência e mudanças de classe", "Latencia y cambios de clase"),
    "Latency improvement": ("Melhoria de latência", "Mejora de latencia"),
    "The network latency buffer when using skills will be changed to operate up to 250~300ms.": ("O buffer de latência de rede ao usar skills passará a operar até 250~300 ms.", "El búfer de latencia de red al usar skills pasará a funcionar hasta 250~300 ms."),
    "The skill failure rate when using the Healer's Superior Divine Will will be improved.": ("A taxa de falha de skills ao usar Superior Divine Will de Healer será reduzida.", "Se reducirá la tasa de fallo de skills al usar Superior Divine Will de Healer."),
    "The skill cannot be cancelled with a dodge skill until the animation is fully complete.": ("A skill não poderá ser cancelada com uma skill de esquiva até o fim da animação.", "La skill no podrá cancelarse con una skill de evasión hasta que termine la animación."),
    "The party member damage increase aura will be removed.": ("A aura de aumento de dano dos membros do grupo será removida.", "Se eliminará el aura de aumento de daño de los miembros del grupo."),
    "All damage increases by an additional 12% during its duration.": ("Todo o dano aumenta em mais 12% durante o efeito.", "Todo el daño aumenta un 12 % adicional durante el efecto."),
    "Ragnarok Points can be accumulated during its duration.": ("Ragnarok Points podem ser acumulados durante o efeito.", "Se pueden acumular Ragnarok Points durante el efecto."),
    "When Ragnarok Points reaches 1000, press the Ragnarok button to use 'Godsfall: Wrath of the Red Moon'.": ("Ao atingir 1.000 Ragnarok Points, pressione o botão de Ragnarok para usar 'Godsfall: Wrath of the Red Moon'.", "Al alcanzar 1000 Ragnarok Points, pulsa el botón de Ragnarok para usar 'Godsfall: Wrath of the Red Moon'."),
    "There may be cases where it appears unusable even when Ragnarok Points is at 1000, but pressing the button will use it normally.": ("Mesmo com 1.000 Ragnarok Points, a skill pode parecer indisponível; ainda assim, pressionar o botão fará com que ela seja usada normalmente.", "Incluso con 1000 Ragnarok Points, la skill puede parecer no disponible; aun así, al pulsar el botón se usará normalmente."),
    "Ragnarok will be sealed for 60 seconds after Godsfall ends.": ("Ragnarok ficará selado por 60 segundos após o término de Godsfall.", "Ragnarok quedará sellado durante 60 segundos tras finalizar Godsfall."),
    "The existing 2nd hit of Godsfall (Calamity Thrust) will be changed to allow exploding Runemarks.": ("O segundo golpe de Godsfall (Calamity Thrust) passará a explodir Runemarks.", "El segundo golpe de Godsfall (Calamity Thrust) podrá hacer explotar Runemarks."),
    "Exploding maximum Runemarks additionally increases Calamity Thrust damage. (approx. +50%)": ("Explodir o máximo de Runemarks também aumenta o dano de Calamity Thrust em cerca de 50%.", "Hacer explotar el máximo de Runemarks también aumenta el daño de Calamity Thrust aproximadamente un 50 %."),
    "Runemark explosion during Godsfall.": ("Explosão de Runemarks durante Godsfall.", "Explosión de Runemarks durante Godsfall."),
    "Can only be used when Ragnarok Points reaches 1000 after activating Godsfall.": ("Só pode ser usada ao atingir 1.000 Ragnarok Points após ativar Godsfall.", "Solo puede usarse al alcanzar 1000 Ragnarok Points después de activar Godsfall."),
    "Using it makes the 2nd hit of Godsfall (Calamity Thrust) unavailable.": ("Ao usá-la, o segundo golpe de Godsfall (Calamity Thrust) fica indisponível.", "Al usarla, el segundo golpe de Godsfall (Calamity Thrust) deja de estar disponible."),
    "Cannot be used simultaneously with the Ragnarok effect.": ("Não pode ser usada ao mesmo tempo que o efeito de Ragnarok.", "No puede usarse al mismo tiempo que el efecto de Ragnarok."),
    "Ragnarok will be sealed for 60 seconds after Wrath of the Red Moon ends.": ("Ragnarok ficará selado por 60 segundos após o término de Wrath of the Red Moon.", "Ragnarok quedará sellado durante 60 segundos tras finalizar Wrath of the Red Moon."),
    "Using Wrath of the Red Moon changes Shining Crescent to 'New Moon: Wrath of Moonlight'. (approx. +10% attack power)": ("Usar Wrath of the Red Moon transforma Shining Crescent em 'New Moon: Wrath of Moonlight', com cerca de 10% a mais de Poder de Ataque.", "Usar Wrath of the Red Moon transforma Shining Crescent en 'New Moon: Wrath of Moonlight', con aproximadamente un 10 % más de Poder de Ataque."),
    "There is an issue where the cooldown displays as 1 second in the skill UI, but it actually applies correctly, same as Shining Crescent.": ("Há um problema visual que mostra cooldown de 1 segundo na interface, mas o valor real é aplicado corretamente, igual ao de Shining Crescent.", "Hay un problema visual que muestra 1 segundo de cooldown en la interfaz, pero el valor real se aplica correctamente, igual que en Shining Crescent."),
    "Shining Crescent changes during Wrath of the Red Moon.": ("Alteração de Shining Crescent durante Wrath of the Red Moon.", "Cambio de Shining Crescent durante Wrath of the Red Moon."),
    "STR +16% / Attack Speed +40 / Attack Range +20% / Skill cooldown under 60 sec reduced by 60%": ("Força +16% / Velocidade de Ataque +40 / Alcance de Ataque +20% / Cooldown de skills abaixo de 60 s reduzido em 60%", "Fuerza +16 % / Velocidad de Ataque +40 / Alcance de Ataque +20 % / Cooldown de skills inferior a 60 s reducido un 60 %"),
    "System changes and bug fixes": ("Mudanças de sistema e correções de bugs", "Cambios de sistema y correcciones de bugs"),
    "Gold cap": ("Limite de Gold", "Límite de Gold"),
    "The maximum gold cap will increase from 100,000,000 gold to 10,000,000,000 gold.": ("O limite máximo aumentará de 100.000.000 para 10.000.000.000 de Gold.", "El límite máximo aumentará de 100.000.000 a 10.000.000.000 de Gold."),
    "The amount that can be collected at once from the Trade Broker will also be changed accordingly.": ("O valor que pode ser coletado de uma só vez no Trade Broker será ajustado de acordo.", "La cantidad que se puede recoger de una vez en el Trade Broker se ajustará en consecuencia."),
    "Fixed an issue where pet effect cooldowns were applying as 88 seconds.": ("Corrigido o problema que aplicava 88 segundos de cooldown aos efeitos de pets.", "Se corrigió el problema que aplicaba 88 segundos de cooldown a los efectos de pets."),
    "Fixed an issue where guild quest text strings were displaying incorrectly.": ("Corrigido o problema de exibição incorreta dos textos de missões de guilda.", "Se corrigió la visualización incorrecta de los textos de misiones de gremio."),
    "Fixed an issue where HP recovery increase effects from runes and equipment were not functioning.": ("Corrigido o problema que impedia o funcionamento dos efeitos de aumento da recuperação de HP de Runas e equipamentos.", "Se corrigió el problema que impedía funcionar los efectos de aumento de recuperación de HP de Runas y equipamiento."),
    "Fixed an issue where the Trial Dungeon reward list did not match actual rewards.": ("Corrigido o problema em que a lista de recompensas da Trial Dungeon não correspondia às recompensas recebidas.", "Se corrigió el problema por el que la lista de recompensas de Trial Dungeon no coincidía con las recompensas recibidas."),
    "Fixed an issue where the camera angle reset button was not working.": ("Corrigido o botão de redefinição do ângulo da câmera.", "Se corrigió el botón para restablecer el ángulo de la cámara."),
    "Fixed an issue where Raging Dragon and Heroic Oath equipment given via quests were displayed as option-changeable.": ("Corrigida a exibição incorreta de que equipamentos Raging Dragon e Heroic Oath recebidos em missões permitiam alterar opções.", "Se corrigió la indicación incorrecta de que el equipamiento Raging Dragon y Heroic Oath recibido en misiones permitía cambiar opciones."),
    "Fixed an issue where healer classes could maintain party buffs when switching equipment.": ("Corrigido o problema que permitia às classes Healer manter buffs do grupo ao trocar de equipamento.", "Se corrigió el problema que permitía a las clases Healer mantener buffs de grupo al cambiar de equipamiento."),
    "With this change, buffs will be removed not only when the healer switches equipment, but also when party members do.": ("Com a mudança, os buffs serão removidos quando o Healer ou qualquer membro do grupo trocar de equipamento.", "Con este cambio, los buffs se eliminarán cuando el Healer o cualquier miembro del grupo cambie de equipamiento."),

    # B134.03
    "Dungeon reward and transition fixes": ("Ajustes de transição e recompensas de Dungeons", "Ajustes de transición y recompensas de Dungeons"),
    "Fixed an issue where clearing the dungeon would move players inside Velika.": ("Corrigido o problema que movia os jogadores para dentro de Velika ao concluir a Dungeon.", "Se corrigió el problema que trasladaba a los jugadores al interior de Velika al completar la Dungeon."),
    "Auto Matchmaking Dungeons": ("Dungeons de Matchmaking Automático", "Dungeons de Matchmaking Automático"),
    "Reward amounts from Auto Matchmaking Dungeons have been increased.": ("As recompensas das Dungeons de Matchmaking Automático foram aumentadas.", "Se aumentaron las recompensas de las Dungeons de Matchmaking Automático."),
    "Vanguard Request rewards have been changed.": ("As recompensas de Vanguard Request foram alteradas.", "Se cambiaron las recompensas de Vanguard Request."),
    "Ace Dungeon": ("Ace Dungeon", "Ace Dungeon"),
    "Rewards have been changed.": ("As recompensas foram alteradas.", "Se cambiaron las recompensas."),

    # B135 - resumo e Dungeons
    "B135 at a glance": ("B135 em resumo", "Resumen de B135"),
    "Dungeon progression": ("Progressão nas Dungeons", "Progresión en Dungeons"),
    "HARD I and HARD II difficulty tiers are now available for eligible dungeons.": ("As dificuldades HARD I e HARD II agora estão disponíveis nas Dungeons elegíveis.", "Las dificultades HARD I y HARD II ya están disponibles en las Dungeons compatibles."),
    "HARD I — Level 950": ("HARD I — Nível 950", "HARD I — Nivel 950"),
    "HARD II — Level 1000": ("HARD II — Nível 1000", "HARD II — Nivel 1000"),
    "New-player bonuses now apply through 15 clears, with extra party rewards.": ("Os bônus para iniciantes agora valem até a 15ª conclusão e concedem recompensas extras ao grupo.", "Los bonos para principiantes ahora se aplican hasta la 15.ª finalización y otorgan recompensas adicionales al grupo."),
    "Several dungeons received pacing, difficulty, and drop adjustments.": ("Várias Dungeons receberam ajustes de ritmo, dificuldade e drops.", "Varias Dungeons recibieron ajustes de ritmo, dificultad y drops."),
    "Build impact": ("Impacto nas builds", "Impacto en las builds"),
    "Sorcerer, Archer, Valkyrie, Priest, Mystic, and Warrior were adjusted.": ("Sorcerer, Archer, Valkyrie, Priest, Mystic e Warrior receberam ajustes.", "Sorcerer, Archer, Valkyrie, Priest, Mystic y Warrior recibieron ajustes."),
    "Healer Strength and Tanker Endurance scaling were redesigned.": ("O escalonamento de Força dos Healers e de Resistência dos Tankers foi reformulado.", "Se rediseñó el escalado de Fuerza de los Healers y de Resistencia de los Tankers."),
    "Accessory Etchings and stronger Annihilation armor stats were added.": ("Foram adicionados Etchings de acessórios e atributos melhores nas armaduras Annihilation.", "Se añadieron Etchings de accesorios y mejores atributos en las armaduras Annihilation."),
    "The most impactful changes are the HARD difficulty tiers and the new healer/tanker stat scaling. Review those tabs before rebuilding gear.": ("As mudanças de maior impacto são as dificuldades HARD e o novo escalonamento de atributos de Healers e Tankers. Consulte essas abas antes de refazer seus equipamentos.", "Los cambios de mayor impacto son las dificultades HARD y el nuevo escalado de atributos de Healers y Tankers. Revisa esas pestañas antes de rehacer tu equipamiento."),
    "New-player support and Vanguard reputation": ("Suporte a iniciantes e reputação Vanguard", "Ayuda para principiantes y reputación Vanguard"),
    "Defeating field monsters in level 500~700 dungeons now grants Vanguard Initiative reputation points.": ("Derrotar monstros comuns em Dungeons de nível 500~700 agora concede pontos de reputação da Vanguard Initiative.", "Derrotar monstruos comunes en Dungeons de nivel 500~700 ahora otorga puntos de reputación de Vanguard Initiative."),
    "The dungeon newbie bonus threshold has been increased from 5 clears to 15 clears.": ("O limite do bônus de iniciante nas Dungeons aumentou de 5 para 15 conclusões.", "El límite del bono de principiante en Dungeons aumentó de 5 a 15 finalizaciones."),
    "If even one party member has fewer than 15 clears, the party receives an additional 50% reward.": ("Se ao menos um membro do grupo tiver menos de 15 conclusões, todo o grupo receberá 50% a mais de recompensas.", "Si al menos un miembro del grupo tiene menos de 15 finalizaciones, todo el grupo recibe un 50 % más de recompensas."),
    "Beginners gain a 25% increase to HP and Attack Power.": ("Iniciantes recebem 25% a mais de HP e Poder de Ataque.", "Los principiantes reciben un 25 % más de HP y Poder de Ataque."),
    "Applies to party dungeons with item level 500~850.": ("Aplica-se às Dungeons de grupo com nível de item 500~850.", "Se aplica a las Dungeons de grupo con nivel de ítem 500~850."),
    "Vanguard Initiative reputation points have been added as drop rewards in the following dungeons.": ("Pontos de reputação da Vanguard Initiative foram adicionados aos drops das seguintes Dungeons.", "Se añadieron puntos de reputación de Vanguard Initiative a los drops de las siguientes Dungeons."),
    "The wave phase before the 1st boss has been reduced.": ("A fase de ondas antes do primeiro chefe foi encurtada.", "Se acortó la fase de oleadas anterior al primer jefe."),
    "The 1st boss Putrion's HP has been significantly reduced.": ("O HP de Putrion, o primeiro chefe, foi reduzido significativamente.", "El HP de Putrion, el primer jefe, se redujo considerablemente."),
    "Vanguard Initiative reputation points have been added as a drop reward.": ("Pontos de reputação da Vanguard Initiative foram adicionados aos drops.", "Se añadieron puntos de reputación de Vanguard Initiative a los drops."),
    "Drop rates for Annihilation Dust and Darkshard have been increased.": ("As chances de drop de Annihilation Dust e Darkshard foram aumentadas.", "Se aumentaron las probabilidades de drop de Annihilation Dust y Darkshard."),
    "You can obtain Condensed Legacy of Annihilation and Condensed Dungeon Core.": ("É possível obter Condensed Legacy of Annihilation e Condensed Dungeon Core.", "Se pueden obtener Condensed Legacy of Annihilation y Condensed Dungeon Core."),
    "You can obtain a large amount of Tier 1 Annihilation Material.": ("É possível obter uma grande quantidade de Annihilation Material de Tier 1.", "Se puede obtener una gran cantidad de Annihilation Material de Tier 1."),
    "You can obtain Rune Material.": ("É possível obter materiais de Runa.", "Se pueden obtener materiales de Runa."),
    "Rewards equivalent to a level 950 dungeon are granted.": ("As recompensas são equivalentes às de uma Dungeon de nível 950.", "Las recompensas equivalen a las de una Dungeon de nivel 950."),
    "There is no resurrection or recovery penalty.": ("Não há penalidade de ressurreição ou recuperação.", "No hay penalización de resurrección ni recuperación."),
    "Drop rewards are increased by an additional +50%.": ("As recompensas de drop recebem um aumento adicional de 50%.", "Las recompensas de drop aumentan un 50 % adicional."),
    "Darkshard Enhancement Stone is guaranteed to drop.": ("O drop de Darkshard Enhancement Stone é garantido.", "El drop de Darkshard Enhancement Stone está garantizado."),
    "1st Boss": ("Primeiro chefe", "Primer jefe"),
    "2nd Boss": ("Segundo chefe", "Segundo jefe"),
    "3rd Boss": ("Terceiro chefe", "Tercer jefe"),
    "Damage from the outer field has been increased.": ("O dano da área externa foi aumentado.", "Se aumentó el daño de la zona exterior."),
    "Damage from the poison field has been increased.": ("O dano da área de veneno foi aumentado.", "Se aumentó el daño de la zona de veneno."),
    "The curse pattern effect now applies immediately after combat begins.": ("O efeito da mecânica de maldição agora é aplicado imediatamente após o início do combate.", "El efecto de la mecánica de maldición ahora se aplica inmediatamente después de iniciar el combate."),
    "The defeat cutscene no longer plays.": ("A cutscene de derrota não será mais exibida.", "Ya no se reproducirá la cinemática de derrota."),
    "Damage from the sweep attack has been significantly increased.": ("O dano do ataque de varredura foi aumentado significativamente.", "El daño del ataque de barrido aumentó considerablemente."),
    "Damage from the laser attack has been significantly increased.": ("O dano do ataque de laser foi aumentado significativamente.", "El daño del ataque láser aumentó considerablemente."),
    "Damage from the magic circle attack has been increased.": ("O dano do ataque do círculo mágico foi aumentado.", "Se aumentó el daño del ataque del círculo mágico."),
    "Base attack power has been lowered.": ("O Poder de Ataque base foi reduzido.", "Se redujo el Poder de Ataque base."),
    "The minigame has been removed.": ("O minigame foi removido.", "Se eliminó el minijuego."),
    "Field monsters now drop rewards.": ("Os monstros comuns agora concedem drops.", "Los monstruos comunes ahora otorgan drops."),
    "Fixed an issue where the Ice Throne Reset Scroll could be obtained here.": ("Corrigido o problema que permitia obter o Reset Scroll de Ice Throne nesta Dungeon.", "Se corrigió el problema que permitía obtener el Reset Scroll de Ice Throne en esta Dungeon."),
    "Boss base attack power has been increased.": ("O Poder de Ataque base dos chefes foi aumentado.", "Se aumentó el Poder de Ataque base de los jefes."),
    "Leaderboard records are only tracked in HARD II.": ("Os recordes do ranking só serão registrados no HARD II.", "Los récords del ranking solo se registrarán en HARD II."),
    "Targeted fixed damage has been significantly increased.": ("O dano fixo direcionado foi aumentado significativamente.", "El daño fijo dirigido aumentó considerablemente."),
    "Field-type fixed damage has been significantly increased.": ("O dano fixo em área foi aumentado significativamente.", "El daño fijo de área aumentó considerablemente."),
    "This dungeon is level 950, so a Tier 1 difficulty adjustment is not possible.": ("Esta Dungeon já é de nível 950, portanto não permite o ajuste de dificuldade Tier 1.", "Esta Dungeon ya es de nivel 950, por lo que no admite el ajuste de dificultad Tier 1."),
    "HARD II can be applied.": ("É possível aplicar o HARD II.", "Se puede aplicar HARD II."),
    "Ace Dungeons now have a low chance to award a normal dungeon reward box matching the dungeon's level.": ("Ace Dungeons agora têm uma pequena chance de conceder uma caixa de recompensas de Dungeon normal correspondente ao nível da Dungeon.", "Las Ace Dungeons ahora tienen una pequeña probabilidad de otorgar una caja de recompensas de Dungeon normal correspondiente a su nivel."),
    "Defeating the final boss grants Vanguard Initiative reputation points.": ("Derrotar o chefe final concede pontos de reputação da Vanguard Initiative.", "Derrotar al jefe final otorga puntos de reputación de Vanguard Initiative."),
    "Vanguard Requests rewards have been changed.": ("As recompensas das Vanguard Requests foram alteradas.", "Se cambiaron las recompensas de las Vanguard Requests."),
    "Additional style rewards": ("Recompensas visuais adicionais", "Recompensas visuales adicionales"),
    "Style: Blazing Flame/Frost weapon boxes now drop.": ("Caixas de armas Style: Blazing Flame/Frost agora podem ser obtidas como drop.", "Las cajas de armas Style: Blazing Flame/Frost ahora pueden obtenerse como drop."),
    "Style: Evil God style armor now drops.": ("A armadura Style: Evil God agora pode ser obtida como drop.", "La armadura Style: Evil God ahora puede obtenerse como drop."),
    "Style: Evil God helmet and cape now drop.": ("O elmo e a capa Style: Evil God agora podem ser obtidos como drop.", "El casco y la capa Style: Evil God ahora pueden obtenerse como drop."),
    "Style: Evil God weapon now drops.": ("A arma Style: Evil God agora pode ser obtida como drop.", "El arma Style: Evil God ahora puede obtenerse como drop."),
    "Can only be worn by Lancers.": ("Pode ser equipada apenas por Lancers.", "Solo puede equiparse con Lancers."),
    "Matchmaking": ("Matchmaking", "Matchmaking"),
    "Warriors can now queue for party matching in the Tanker role.": ("Warriors agora podem entrar no matchmaking de grupo na função Tanker.", "Los Warriors ahora pueden entrar al matchmaking de grupo con la función Tanker."),
    "However, the +100% dungeon entry count bonus normally given to Tanker classes will not apply.": ("Entretanto, o bônus de 100% na quantidade de entradas concedido normalmente aos Tankers não será aplicado.", "Sin embargo, no se aplicará el bono del 100 % en la cantidad de entradas que normalmente reciben los Tankers."),
    "Since Warriors can freely toggle their skills on and off, applying the bonus conditionally would be difficult to control.": ("Como Warriors podem ativar e desativar livremente suas skills, não seria possível controlar o bônus de forma condicional.", "Como los Warriors pueden activar y desactivar libremente sus skills, no sería posible controlar el bono de forma condicional."),
    "In Auto Matchmaking Dungeons, your own gear is now used if its item level is 900 or higher.": ("Nas Dungeons de Matchmaking Automático, seus próprios equipamentos serão usados caso tenham nível de item 900 ou superior.", "En las Dungeons de Matchmaking Automático se usará tu propio equipamiento si tiene nivel de ítem 900 o superior."),

    # B135 - recompensas
    "Island of Dawn and Vanguard rewards": ("Recompensas da Island of Dawn e Vanguard", "Recompensas de Island of Dawn y Vanguard"),
    "Style Etching crafting materials that used to drop from Island of Dawn now drop regardless of monster type.": ("Os materiais de crafting de Style Etching da Island of Dawn agora podem ser obtidos independentemente do tipo de monstro.", "Los materiales de crafting de Style Etching de Island of Dawn ahora se obtienen sin importar el tipo de monstruo."),
    "The three material types drop from any monster, each at a different rate.": ("Os três tipos de material podem vir de qualquer monstro, cada um com uma chance diferente.", "Los tres tipos de material pueden caer de cualquier monstruo, cada uno con una probabilidad diferente."),
    "The shop that uses Dawnstorm Tokens has been reorganized.": ("A loja de Dawnstorm Tokens foi reorganizada.", "Se reorganizó la tienda de Dawnstorm Tokens."),
    "The shop lineup has been refreshed and is now subject to a per-account purchase limit.": ("O catálogo da loja foi renovado e agora possui limite de compra por conta.", "Se renovó el catálogo de la tienda y ahora tiene un límite de compra por cuenta."),
    "The shop lineup resets every 7 days.": ("O catálogo da loja é reiniciado a cada 7 dias.", "El catálogo de la tienda se reinicia cada 7 días."),
    "Available through the merchant NPC stationed at each Island of Dawn regional camp.": ("Disponível no NPC comerciante de cada acampamento regional da Island of Dawn.", "Disponible en el NPC comerciante de cada campamento regional de Island of Dawn."),
    "Item Name": ("Nome do item", "Nombre del ítem"),
    "Dawnstorm Tokens Required": ("Dawnstorm Tokens necessários", "Dawnstorm Tokens necesarios"),
    "7-Day Limit": ("Limite por 7 dias", "Límite por 7 días"),
    "Other weekly shop items": ("Outros itens da loja semanal", "Otros ítems de la tienda semanal"),
    "Gems and all forms of EXP have been removed from the Level 1~64 weekly/daily rewards.": ("Gems e todos os tipos de EXP foram removidos das recompensas diárias e semanais dos níveis 1~64.", "Se eliminaron Gems y todos los tipos de EXP de las recompensas diarias y semanales de los niveles 1~64."),

    # B135 - balanceamento de classes
    "Class balance adjustments": ("Ajustes de balanceamento das classes", "Ajustes de balance de clases"),
    "Passive — Elemental Attunement": ("Passiva — Elemental Attunement", "Pasiva — Elemental Attunement"),
    "The 4% damage increase for Meteor Strike and Ice Lances has been removed.": ("O aumento de 4% no dano de Meteor Strike e Ice Lances foi removido.", "Se eliminó el aumento del 4 % de daño de Meteor Strike e Ice Lances."),
    "Changed to a 15% damage increase on Awakening skill hits instead. (Applies to: Ice Lances / Fusion / Implosion)": ("Em seu lugar, os acertos de skills de Awakening causam 15% a mais de dano. Aplica-se a Ice Lances, Fusion e Implosion.", "En su lugar, los impactos de skills de Awakening infligen un 15 % más de daño. Se aplica a Ice Lances, Fusion e Implosion."),
    "Passive — Burst of Celerity": ("Passiva — Burst of Celerity", "Pasiva — Burst of Celerity"),
    "The attack speed increase of Burst of Celerity has been adjusted at each tier.": ("O aumento de Velocidade de Ataque de Burst of Celerity foi ajustado em cada nível.", "Se ajustó el aumento de Velocidad de Ataque de Burst of Celerity en cada nivel."),
    "Passive — Meteor Strike Enhancement I": ("Passiva — Meteor Strike Enhancement I", "Pasiva — Meteor Strike Enhancement I"),
    "The damage increase when hitting multiple targets has been removed.": ("O aumento de dano ao atingir vários alvos foi removido.", "Se eliminó el aumento de daño al golpear a varios objetivos."),
    "Damage is increased by 20% when Meteor Strike hits.": ("Meteor Strike causa 20% a mais de dano ao acertar.", "Meteor Strike inflige un 20 % más de daño al acertar."),
    "Fixed an issue where Meteor Strike's damage increase effect was not being applied.": ("Corrigido o problema que impedia a aplicação do aumento de dano de Meteor Strike.", "Se corrigió el problema que impedía aplicar el aumento de daño de Meteor Strike."),
    "Buff — Element Zero": ("Buff — Element Zero", "Buff — Element Zero"),
    "Critical rate increase per stack: +15 → +20": ("Aumento da Taxa Crítica por acúmulo: +15 → +20", "Aumento de la Tasa Crítica por acumulación: +15 → +20"),
    "Active — Mana Boost II": ("Ativa — Mana Boost II", "Activa — Mana Boost II"),
    "A 15% Strength increase has been added.": ("Foi adicionado um aumento de 15% de Força.", "Se añadió un aumento del 15 % de Fuerza."),
    "Passive — Safe Space": ("Passiva — Safe Space", "Pasiva — Safe Space"),
    "Fixed an issue where the minimum distance was 7m instead of 5m. (Corrected to 5m)": ("Corrigido o alcance mínimo, que estava em 7 m em vez de 5 m.", "Se corrigió el alcance mínimo, que era de 7 m en vez de 5 m."),
    "The attack power increase rate has been changed from 30% to 50%.": ("O aumento de Poder de Ataque passou de 30% para 50%.", "El aumento de Poder de Ataque pasó del 30 % al 50 %."),
    "Active — Wind Walk": ("Ativa — Wind Walk", "Activa — Wind Walk"),
    "The power increase rate for Radiant Arrow, Arrow Volley, Thunderbolt, and Incendiary Trap Arrow under the Quivering Bowstring effect has been changed from 10% to 25%.": ("Sob o efeito de Quivering Bowstring, o aumento de Poder de Radiant Arrow, Arrow Volley, Thunderbolt e Incendiary Trap Arrow passou de 10% para 25%.", "Bajo el efecto de Quivering Bowstring, el aumento de Poder de Radiant Arrow, Arrow Volley, Thunderbolt e Incendiary Trap Arrow pasó del 10 % al 25 %."),
    "Active — Godsfall: The Wrath of the Red Moon": ("Ativa — Godsfall: The Wrath of the Red Moon", "Activa — Godsfall: The Wrath of the Red Moon"),
    "The unusable cooldown has been changed from 45 seconds to 15 seconds.": ("O tempo de indisponibilidade passou de 45 para 15 segundos.", "El tiempo de indisponibilidad pasó de 45 a 15 segundos."),
    "The Strength increase has been changed from 18% to 25%.": ("O aumento de Força passou de 18% para 25%.", "El aumento de Fuerza pasó del 18 % al 25 %."),
    "The duration has been changed from 25 seconds to 20 seconds.": ("A duração passou de 25 para 20 segundos.", "La duración pasó de 25 a 20 segundos."),
    "Active — Divine Charge": ("Ativa — Divine Charge", "Activa — Divine Charge"),
    "At max charge level, the Strength increase has been changed from 25 to 35.": ("Na carga máxima, o aumento de Força passou de 25 para 35.", "Con la carga máxima, el aumento de Fuerza pasó de 25 a 35."),
    "At max charge level, the duration has been changed from 8 seconds to 10 seconds.": ("Na carga máxima, a duração passou de 8 para 10 segundos.", "Con la carga máxima, la duración pasó de 8 a 10 segundos."),
    "Active — Blessing of Shakan": ("Ativa — Blessing of Shakan", "Activa — Blessing of Shakan"),
    "The Strength increase has been changed from 30 to 33.": ("O aumento de Força passou de 30 para 33.", "El aumento de Fuerza pasó de 30 a 33."),
    "Active — Kaia's Shield": ("Ativa — Kaia's Shield", "Activa — Kaia's Shield"),
    "Shield absorption has been increased by 50% at all levels.": ("A absorção do Escudo aumentou 50% em todos os níveis.", "La absorción del Escudo aumentó un 50 % en todos los niveles."),
    "Grants 0.5 seconds of invincibility and clears reaction states the instant Kaia's Shield is applied.": ("Concede 0,5 segundo de invencibilidade e remove estados de reação no instante em que Kaia's Shield é aplicado.", "Otorga 0,5 segundos de invencibilidad y elimina los estados de reacción al aplicar Kaia's Shield."),
    "Does not stack when used consecutively.": ("O efeito não acumula em usos consecutivos.", "El efecto no se acumula con usos consecutivos."),
    "Active — Edict of Judgment": ("Ativa — Edict of Judgment", "Activa — Edict of Judgment"),
    "The Strength increase has been changed from 60 to 80.": ("O aumento de Força passou de 60 para 80.", "El aumento de Fuerza pasó de 60 a 80."),
    "Active — Thrall of Vengeance": ("Ativa — Thrall of Vengeance", "Activa — Thrall of Vengeance"),
    "The effect duration while Thrall Augmentation is active has been changed from 12 seconds to 13 seconds.": ("Com Thrall Augmentation ativo, a duração do efeito passou de 12 para 13 segundos.", "Con Thrall Augmentation activo, la duración del efecto pasó de 12 a 13 segundos."),
    "Active — Thrall of Wrath": ("Ativa — Thrall of Wrath", "Activa — Thrall of Wrath"),
    "The effect duration while Thrall Augmentation is active has been changed from 20 seconds to 22 seconds.": ("Com Thrall Augmentation ativo, a duração do efeito passou de 20 para 22 segundos.", "Con Thrall Augmentation activo, la duración del efecto pasó de 20 a 22 segundos."),
    "Passive — Enhanced Defensive Stance": ("Passiva — Enhanced Defensive Stance", "Pasiva — Enhanced Defensive Stance"),
    "The power increase rate against monsters in front has been changed from 10% to 40%.": ("O aumento de Poder contra monstros à frente passou de 10% para 40%.", "El aumento de Poder contra monstruos situados delante pasó del 10 % al 40 %."),
    "Active — Defensive Stance": ("Ativa — Defensive Stance", "Activa — Defensive Stance"),
    "Aggro generation has been further increased substantially.": ("A geração de Aggro foi aumentada consideravelmente.", "La generación de Aggro aumentó considerablemente."),
    "The critical rate correction against monsters has been removed.": ("A correção de Taxa Crítica contra monstros foi removida.", "Se eliminó la corrección de Tasa Crítica contra monstruos."),
    "This change has already been applied on the server side and is live, but the client-side tooltip display has not yet been updated and may still show the pre-update value.": ("A mudança já está ativa no servidor, mas a tooltip do cliente ainda não foi atualizada e pode mostrar o valor anterior.", "El cambio ya está activo en el servidor, pero la tooltip del cliente aún no se ha actualizado y puede mostrar el valor anterior."),

    # B135 - Glifos e escalonamento
    "Glyph and stat scaling changes": ("Mudanças nos Glifos e no escalonamento de atributos", "Cambios en Glifos y escalado de atributos"),
    "Glyph cooldown calculation": ("Cálculo de cooldown dos Glifos", "Cálculo de cooldown de los Glifos"),
    "The calculation method for the \"% reduced skill cooldown\" effect has been changed to multiplicative.": ("O cálculo do efeito de redução percentual do cooldown de skills passou a ser multiplicativo.", "El cálculo del efecto de reducción porcentual del cooldown de skills ahora es multiplicativo."),
    "Example — Using a 100-second skill with a Glyph effect that reduces cooldown by 30% (with a 70% total cooldown reduction already applied from gear)": ("Exemplo: skill de 100 segundos com um Glifo que reduz o cooldown em 30%, após uma redução total de 70% aplicada pelos equipamentos.", "Ejemplo: skill de 100 segundos con un Glifo que reduce el cooldown un 30 %, después de aplicar una reducción total del 70 % por equipamiento."),
    "Case": ("Cenário", "Caso"),
    "Remaining Time": ("Tempo restante", "Tiempo restante"),
    "Before (70% total gear reduction)": ("Antes (70% de redução total dos equipamentos)", "Antes (70 % de reducción total por equipamiento)"),
    "After (70% total gear reduction)": ("Depois (70% de redução total dos equipamentos)", "Después (70 % de reducción total por equipamiento)"),
    "After gear-based cooldown reduction is applied, the Glyph's -30% is then calculated on the remaining 30 seconds.": ("Após aplicar a redução dos equipamentos, os 30% do Glifo são calculados sobre os 30 segundos restantes.", "Tras aplicar la reducción del equipamiento, el 30 % del Glifo se calcula sobre los 30 segundos restantes."),
    "Strength / Endurance stat display": ("Exibição dos atributos Força e Resistência", "Visualización de los atributos Fuerza y Resistencia"),
    "Updated Strength and Endurance stat display.": ("Nova exibição dos atributos Força e Resistência.", "Nueva visualización de los atributos Fuerza y Resistencia."),
    "The stat display format has been changed.": ("O formato de exibição dos atributos foi alterado.", "Se cambió el formato de visualización de los atributos."),
    "Before: Base + Total Increased Stat Value": ("Antes: Base + valor total de aumento do atributo", "Antes: Base + valor total de aumento del atributo"),
    "After: Base + Gear Total Value + Buff Stat Value": ("Depois: Base + valor total dos equipamentos + valor dos buffs", "Después: Base + valor total del equipamiento + valor de los buffs"),
    "Since buff stats are not included in scaling, this change is made to prevent confusion.": ("Como os atributos de buffs não entram no escalonamento, a exibição foi alterada para evitar confusão.", "Como los atributos de buffs no se incluyen en el escalado, se cambió la visualización para evitar confusiones."),
    "The white-colored stat value is the figure that actually generates scaling-based efficiency.": ("O valor exibido em branco é o que efetivamente gera eficiência no escalonamento.", "El valor mostrado en blanco es el que realmente genera eficiencia en el escalado."),
    "Healer Strength scaling": ("Escalonamento de Força dos Healers", "Escalado de Fuerza de los Healers"),
    "The scaling starting threshold has been changed from 300 to 200.": ("O valor inicial do escalonamento passou de 300 para 200.", "El valor inicial del escalado pasó de 300 a 200."),
    "A cap has been applied depending on the scaling range.": ("Foi aplicado um limite conforme a faixa de escalonamento.", "Se aplicó un límite según el rango de escalado."),
    "The cap does not apply to damage amplification stats.": ("O limite não se aplica aos atributos de Amplificação de Dano.", "El límite no se aplica a los atributos de Amplificación de Daño."),
    "For every 1 point of Strength, the following efficiency increase is applied.": ("Para cada ponto de Força, aplica-se o aumento de eficiência indicado abaixo.", "Por cada punto de Fuerza se aplica el aumento de eficiencia indicado a continuación."),
    "Strength 200~500 range: 1%": ("Faixa de Força 200~500: 1%", "Rango de Fuerza 200~500: 1 %"),
    "Strength 500~600 range: 0.5%": ("Faixa de Força 500~600: 0,5%", "Rango de Fuerza 500~600: 0,5 %"),
    "Strength (Power)": ("Força (Poder)", "Fuerza (Poder)"),
    "Buff Amount Increase": ("Aumento do valor dos buffs", "Aumento del valor de los buffs"),
    "100 or below": ("100 ou menos", "100 o menos"),
    "+0% (no bonus)": ("+0% (sem bônus)", "+0 % (sin bono)"),
    "200 (noticeable effect begins)": ("200 (início do efeito perceptível)", "200 (inicio del efecto perceptible)"),
    "500 (soft cap)": ("500 (limite suave)", "500 (límite suave)"),
    "600 (hard cap)": ("600 (limite rígido)", "600 (límite estricto)"),
    "650 or above (hard cap, no further increase)": ("650 ou mais (limite rígido, sem aumento adicional)", "650 o más (límite estricto, sin aumento adicional)"),
    "The duration of Taunt skills has been reduced by 50% compared to before. (36 sec → 18 sec)": ("A duração das skills de Taunt foi reduzida em 50%: de 36 para 18 segundos.", "La duración de las skills de Taunt se redujo un 50 %: de 36 a 18 segundos."),
    "After a Taunt skill is applied to a monster, it will not be taunted again by a Taunt skill for a set period of time.": ("Após receber uma skill de Taunt, o monstro ficará imune a novos Taunts por determinado período.", "Tras recibir una skill de Taunt, el monstruo será inmune a nuevos Taunts durante un periodo determinado."),
    "Taunt skills from other classes are likewise subject to this immunity for the duration.": ("Skills de Taunt de outras classes também serão afetadas por essa imunidade.", "Las skills de Taunt de otras clases también estarán sujetas a esta inmunidad."),
    "Natural aggro generated by a monster's HP decreasing remains unchanged at 36 seconds.": ("O Aggro natural gerado pela redução do HP do monstro permanece com duração de 36 segundos.", "El Aggro natural generado al reducir el HP del monstruo mantiene una duración de 36 segundos."),
    "The source describes the Tanker Endurance cap in two different ways: no additional efficiency beyond 550, but later a soft cap from 500~600 and a hard cap at 600. Confirm the effective breakpoint in game.": ("A fonte descreve o limite de Resistência dos Tankers de duas formas: sem eficiência adicional acima de 550, mas depois indica limite suave entre 500~600 e limite rígido em 600. Confirme o ponto efetivo dentro do jogo.", "La fuente describe el límite de Resistencia de los Tankers de dos formas: sin eficiencia adicional por encima de 550, pero después indica un límite suave entre 500~600 y un límite estricto en 600. Confirma el punto efectivo dentro del juego."),
    "Tanker Endurance scaling": ("Escalonamento de Resistência dos Tankers", "Escalado de Resistencia de los Tankers"),
    "Tanker classes now gain additional effects proportional to their Endurance stat.": ("Classes Tanker agora recebem efeitos adicionais proporcionais ao atributo Resistência.", "Las clases Tanker ahora reciben efectos adicionales proporcionales al atributo Resistencia."),
    "Increased Taunt duration when using a Taunt skill": ("Aumento da duração do Taunt ao usar uma skill de Taunt", "Aumento de la duración del Taunt al usar una skill de Taunt"),
    "Increased uptime for Perfect Defense effects": ("Aumento da duração dos efeitos de Perfect Defense", "Aumento de la duración de los efectos de Perfect Defense"),
    "Amplified damage reduction effect on weapon gear while blocking": ("Maior redução de dano do efeito da arma durante o bloqueio", "Mayor reducción de daño del efecto del arma al bloquear"),
    "Additional effects depending on class": ("Efeitos adicionais conforme a classe", "Efectos adicionales según la clase"),
    "The Tanker class Endurance stat threshold starts applying from 200.": ("O escalonamento de Resistência dos Tankers começa em 200.", "El escalado de Resistencia de los Tankers comienza en 200."),
    "No additional efficiency is granted beyond 550 Endurance.": ("Não há eficiência adicional acima de 550 de Resistência.", "No se obtiene eficiencia adicional por encima de 550 de Resistencia."),
    "Common Effects": ("Efeitos comuns", "Efectos comunes"),
    "The effects below are examples by Endurance range. Efficiency increases proportionally even if Endurance is raised by just 1 point.": ("Os valores abaixo são exemplos por faixa de Resistência. A eficiência aumenta proporcionalmente a cada ponto adicional.", "Los valores siguientes son ejemplos por rango de Resistencia. La eficiencia aumenta proporcionalmente con cada punto adicional."),
    "Example — At 300 Endurance, Perfect Defense's bonus duration is increased by 0.1 seconds.": ("Exemplo: com 300 de Resistência, a duração adicional de Perfect Defense aumenta em 0,1 segundo.", "Ejemplo: con 300 de Resistencia, la duración adicional de Perfect Defense aumenta 0,1 segundos."),
    "For every 1 point of Endurance, the following efficiency is increased.": ("A eficiência abaixo aumenta a cada ponto de Resistência.", "La eficiencia siguiente aumenta con cada punto de Resistencia."),
    "200~500 range": ("Faixa 200~500", "Rango 200~500"),
    "Efficiency increase per 1 Endurance": ("Aumento por ponto de Resistência", "Aumento por punto de Resistencia"),
    "Taunt Duration": ("Duração do Taunt", "Duración del Taunt"),
    "Perfect Defense Bonus Duration": ("Duração adicional de Perfect Defense", "Duración adicional de Perfect Defense"),
    "Weapon Defense Efficiency": ("Eficiência defensiva da arma", "Eficiencia defensiva del arma"),
    "Defense Efficiency (Lancer)": ("Eficiência de Defesa (Lancer)", "Eficiencia de Defensa (Lancer)"),
    "Own Attack Power Increase (Brawler, Warrior)": ("Aumento do próprio Poder de Ataque (Brawler, Warrior)", "Aumento del Poder de Ataque propio (Brawler, Warrior)"),
    "From the 500~600 range, a soft cap applies and the above values are halved.": ("Na faixa 500~600, aplica-se um limite suave e os valores acima são reduzidos pela metade.", "En el rango 500~600 se aplica un límite suave y los valores anteriores se reducen a la mitad."),
    "From the 600 range, a hard cap applies and no further increase occurs.": ("A partir de 600, aplica-se um limite rígido e não há novos aumentos.", "A partir de 600 se aplica un límite estricto y no hay más aumentos."),
    "Endurance": ("Resistência", "Resistencia"),
    "Taunt Duration (Total)": ("Duração total do Taunt", "Duración total del Taunt"),
    "200 or below": ("200 ou menos", "200 o menos"),
    "The efficiency of the Armor Break skill has been increased.": ("A eficiência da skill Armor Break foi aumentada.", "Se aumentó la eficiencia de la skill Armor Break."),
    "Armor Break is 6% × 2 stacks, with each stack applying separately.": ("Armor Break aplica 6% × 2 acúmulos, calculados separadamente.", "Armor Break aplica 6 % × 2 acumulaciones, calculadas por separado."),
    "Example — At 500 Endurance, 12% + 12% combine for 24% efficiency.": ("Exemplo: com 500 de Resistência, 12% + 12% resultam em 24% de eficiência.", "Ejemplo: con 500 de Resistencia, 12 % + 12 % resultan en un 24 % de eficiencia."),
    "Armor Break Efficiency Increase": ("Aumento de eficiência de Armor Break", "Aumento de eficiencia de Armor Break"),
    "500 (cap)": ("500 (limite)", "500 (límite)"),
    "Warrior and Brawler": ("Warrior e Brawler", "Warrior y Brawler"),
    "Passive attack power is increased.": ("O Poder de Ataque passivo é aumentado.", "Se aumenta el Poder de Ataque pasivo."),
    "For Warrior, this only applies while the Defensive Stance skill effect is active.": ("Para Warrior, aplica-se apenas enquanto o efeito de Defensive Stance estiver ativo.", "Para Warrior, solo se aplica mientras el efecto de Defensive Stance esté activo."),
    "Stacks additively on top of the base effect.": ("O bônus é somado ao efeito base.", "El bono se suma al efecto base."),
    "Own Attack Power Increase": ("Aumento do próprio Poder de Ataque", "Aumento del Poder de Ataque propio"),

    # B135 - itens e sistema
    "Items and Etchings": ("Itens e Etchings", "Ítems y Etchings"),
    "Accessory Etchings": ("Etchings de Acessório", "Etchings de Accesorio"),
    "Necklace, Earring, Ring, Belt, and Brooch Etchings have been added.": ("Foram adicionados Etchings para Colar, Brinco, Anel, Cinto e Broche.", "Se añadieron Etchings para Collar, Pendiente, Anillo, Cinturón y Broche."),
    "Grade": ("Grau", "Grado"),
    "Endurance Increase": ("Aumento de Resistência", "Aumento de Resistencia"),
    "Annihilation Gear": ("Equipamentos Annihilation", "Equipamiento Annihilation"),
    "The bonus stat effect gained from enhancing armor and boots has been increased.": ("Os atributos adicionais obtidos ao aprimorar armaduras e botas foram aumentados.", "Se aumentaron los atributos adicionales obtenidos al mejorar armaduras y botas."),
    "Endurance — doubled compared to before.": ("Resistência: o dobro do valor anterior.", "Resistencia: el doble del valor anterior."),
    "Critical Resistance — tripled compared to before.": ("Resistência Crítica: o triplo do valor anterior.", "Resistencia Crítica: el triple del valor anterior."),
    "System changes and fixes": ("Mudanças e correções do sistema", "Cambios y correcciones del sistema"),
    "Mail": ("Correio", "Correo"),
    "A bulk-delete feature for mail has been added.": ("Foi adicionada a exclusão de mensagens em massa.", "Se añadió la eliminación masiva de mensajes."),
    "You can bulk-delete mail that has no attached items or gold.": ("É possível excluir em massa mensagens sem itens ou Gold anexados.", "Se pueden eliminar en masa los mensajes sin ítems ni Gold adjuntos."),
    "Deleted mail cannot be restored, so please proceed with caution.": ("Mensagens excluídas não podem ser recuperadas. Use o recurso com cuidado.", "Los mensajes eliminados no se pueden recuperar. Usa la función con cuidado."),
    "Shop": ("Loja", "Tienda"),
    "Fixed an issue where the UI would not respond when attempting to purchase again without changing tabs after a purchase.": ("Corrigido o problema que travava a interface ao tentar comprar novamente sem trocar de aba.", "Se corrigió el problema que bloqueaba la interfaz al intentar comprar de nuevo sin cambiar de pestaña."),
    "Fixed an issue where an item level was displayed for equipment listed in the shop.": ("Corrigida a exibição indevida de nível de item nos equipamentos da loja.", "Se corrigió la visualización indebida de nivel de ítem en el equipamiento de la tienda."),
    "Runes": ("Runas", "Runas"),
    "Fixed an issue where locked options would intermittently become unlocked while changing rune options.": ("Corrigido o problema que desbloqueava ocasionalmente opções protegidas ao alterar opções de Runa.", "Se corrigió el problema que desbloqueaba ocasionalmente opciones protegidas al cambiar opciones de Runa."),
    "Fixed an issue where accessory rune disassembly rewards were not granted.": ("Corrigido o problema que impedia o recebimento das recompensas ao desmontar Runas de Acessório.", "Se corrigió el problema que impedía recibir recompensas al desmantelar Runas de Accesorio."),
    "Now applies the same as existing armor/weapon runes.": ("O funcionamento agora segue o mesmo padrão das Runas de armadura e arma.", "Ahora funciona igual que las Runas de armadura y arma."),
    "Fixed an issue where only the first letter could be capitalized when entering an English nickname.": ("Corrigido o problema que permitia usar letra maiúscula apenas no primeiro caractere de apelidos em inglês.", "Se corrigió el problema que solo permitía usar mayúscula en la primera letra de los apodos en inglés."),
    "Changed so that a blocked opponent can no longer send you a duel request.": ("Jogadores bloqueados não poderão mais enviar solicitações de duelo.", "Los jugadores bloqueados ya no podrán enviar solicitudes de duelo."),
}


def traduzir_texto(texto: str, idioma: str) -> str:
    if texto in TRADUCOES:
        return TRADUCOES[texto][0 if idioma == "pt-BR" else 1]

    correspondencia = re.fullmatch(r"Account (\d+)x", texto)
    if correspondencia:
        quantidade = correspondencia.group(1)
        return f"{quantidade}x por conta" if idioma == "pt-BR" else f"{quantidade}x por cuenta"

    correspondencia = re.fullmatch(r"Character (\d+)x", texto)
    if correspondencia:
        quantidade = correspondencia.group(1)
        return f"{quantidade}x por personagem" if idioma == "pt-BR" else f"{quantidade}x por personaje"

    correspondencia = re.fullmatch(r"(\d+) Players", texto)
    if correspondencia:
        quantidade = correspondencia.group(1)
        return f"{quantidade} jogadores" if idioma == "pt-BR" else f"{quantidade} jugadores"

    correspondencia = re.fullmatch(r"(\d+)-Player Raid", texto)
    if correspondencia:
        quantidade = correspondencia.group(1)
        return f"Raid para {quantidade} jogadores" if idioma == "pt-BR" else f"Raid para {quantidade} jugadores"

    if texto == "Duration: 25 sec":
        return "Duração: 25 s" if idioma == "pt-BR" else "Duración: 25 s"

    correspondencia = re.fullmatch(r"([+]?\d+(?:\.\d+)?) sec", texto)
    if correspondencia:
        valor = correspondencia.group(1).replace(".", ",")
        return f"{valor} s"

    return texto


def localizar_conteudo(valor: Any, idioma: str, chave: str | None = None) -> Any:
    chaves_tecnicas = {"src", "className", "icon", "type", "border", "titleTone", "tone"}
    if isinstance(valor, dict):
        return {
            chave_filha: (
                idioma
                if chave_filha == "locale"
                else valor_filho
                if chave_filha in chaves_tecnicas
                else localizar_conteudo(valor_filho, idioma, chave_filha)
            )
            for chave_filha, valor_filho in valor.items()
        }
    if isinstance(valor, list):
        return [localizar_conteudo(item, idioma, chave) for item in valor]
    if isinstance(valor, str):
        return traduzir_texto(valor, idioma)
    return valor
